//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreativoDBV2Container : DbContext
    {
        public CreativoDBV2Container()
            : base("name=CreativoDBV2Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Forum> Forums { get; set; }
        public virtual DbSet<Forum_Comment> Forum_Comment { get; set; }
        public virtual DbSet<Entrepeneurship_type> Entrepeneurship_type { get; set; }
        public virtual DbSet<Entrepeneurship> Entrepeneurships { get; set; }
        public virtual DbSet<Workshop_photo> Workshop_photo { get; set; }
        public virtual DbSet<Workshop> Workshops { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Entrepeneurship_Admins> Entrepeneurship_Admins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Workshop_Record> Workshop_Record1 { get; set; }
    }
}
