//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum_Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int ForumId { get; set; }
        public int UserId { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual User User { get; set; }
    }
}
