//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class creativoDBEntity : DbContext
    {
        public creativoDBEntity()
            : base("name=creativoDBEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Delivery_Person> Delivery_Persons { get; set; }
        public virtual DbSet<Distric> Districs { get; set; }
        public virtual DbSet<Entrepreneurship> Entrepreneurships { get; set; }
        public virtual DbSet<Entrepreneurship_Admins> Entrepreneurship_Admins { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Workshop> Workshops { get; set; }
        public virtual DbSet<Workshop_Client> Workshop_Client { get; set; }
        public virtual DbSet<Workshop_Photos> Workshop_Photos { get; set; }
        public virtual DbSet<Entrepreneurship_Type> Entrepreneurship_Type { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<Social_Type> Social_Type { get; set; }
        public virtual DbSet<Temp_Pass> Temp_Pass { get; set; }
        public virtual DbSet<WorkshopRecord> WorkshopRecords { get; set; }
    }
}
