//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creativo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShopClient
    {
        public int Id { get; set; }
        public int WorkshopId { get; set; }
        public int UserId { get; set; }
        public string State { get; set; }
        public string lastDigits { get; set; }
        public float price { get; set; }
    
        public virtual User User { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
